### ISSUE TITLE
SoftAdapt.git not found

### ISSUE THREAD

**Issue by KOD1S** [SindiLab/ACTIVA#11]
Hi,

When running 'pip install -r requirements.txt', I am receiving the message:

fatal: repository 'https://github.com/dr-aheydari/SoftAdapt.git/' not found

![image](https://user-images.githubusercontent.com/63750985/193553569-7c38b48d-2b54-4856-bd27-91882f2402a4.png)

Is this still available?

Kind regards,

Richard

**Comment by KOD1S** [comment]
Just to not, when using the links below:
![image](https://user-images.githubusercontent.com/63750985/193555096-21fca43f-1984-497b-ba92-548b06e9ba4d.png)

We get the error:
![image](https://user-images.githubusercontent.com/63750985/193555161-3a8c7869-5138-42ba-bd0a-17c27d5b370c.png)

So switch to the method:
![image](https://user-images.githubusercontent.com/63750985/193555229-31ee5488-86df-413c-8317-b0d52efb221e.png)
In order to connect.

**Comment by dr-aheydari** [comment]
Hi Richard (@KOD1S),

Sorry about this issue! The support for SoftAdapt was recently ended (due to it being a bit outdated with the current torch developments). However, SoftAdapt is only used for adaptive weighting of the loss components, which was not used in the paper (but it can be used to automize the loss scaling). SoftAdapt is fairly straightforward to implement, here's a preprint of the algorithm here: https://arxiv.org/pdf/1912.12355.pdf. 

Thank you for bringing this to my attention! I will update the `requirements.txt.` to remove SoftAdapt as a requirement : )

**Comment by KOD1S** [comment]
Hi @dr-aheydari, thanks for your quick response, however the ACTIVA.py file still calls for SoftAdapt, which is not available.
![image](https://user-images.githubusercontent.com/63750985/194303347-dcb37d7e-b817-4591-9958-29e34c841f27.png)
